apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: medsync
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: auth:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/auth_db"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: medsync-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRE
          valueFrom:
            secretKeyRef:
              name: medsync-secrets
              key: JWT_EXPIRE
        - name: PORT
          value: "5000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: medsync
spec:
  selector:
    app: auth
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
