const crypto = require('crypto');
const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');

const RECEIPT_SECRET = process.env.RECEIPT_SIGNING_SECRET || process.env.JWT_SECRET || 'medsync-receipt-secret';

const formatMoney = (amount = 0, currency = 'lkr') => {
  return `${String(currency || 'lkr').toUpperCase()} ${Number(amount || 0).toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
};

const generateReceiptNumber = () => {
  const now = new Date();
  const stamp = `${now.getUTCFullYear()}${String(now.getUTCMonth() + 1).padStart(2, '0')}${String(now.getUTCDate()).padStart(2, '0')}`;
  const random = crypto.randomBytes(3).toString('hex').toUpperCase();
  return `MS-${stamp}-${random}`;
};

const signReceiptHash = ({ appointmentId, paymentId, amount, currency, paidAt, receiptNumber }) => {
  const raw = [appointmentId, paymentId, amount, currency, paidAt, receiptNumber, RECEIPT_SECRET].join('|');
  return crypto.createHash('sha256').update(raw).digest('hex');
};

const buildReceiptData = (payment, receiptUrl) => {
  const paidAt = payment.updatedAt || payment.createdAt || new Date();
  return {
    receiptNumber: payment.receiptNumber,
    receiptHash: payment.receiptHash,
    paymentId: String(payment._id),
    appointmentId: payment.appointmentId,
    patientId: payment.patientId,
    doctorId: payment.doctorId,
    doctorName: payment.doctorName || 'Doctor',
    amount: Number(payment.amount || 0),
    currency: String(payment.currency || 'lkr').toUpperCase(),
    amountLabel: formatMoney(payment.amount, payment.currency),
    status: payment.status,
    paidAt,
    riskScore: payment.auditInsights?.riskScore || 0,
    riskLevel: payment.auditInsights?.riskLevel || 'low',
    receiptUrl,
  };
};

const generateReceiptPdfBuffer = async (receipt) => {
  const doc = new PDFDocument({ size: 'A4', margin: 48 });
  const chunks = [];

  const completed = new Promise((resolve, reject) => {
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  const qrPayload = JSON.stringify({
    receiptNumber: receipt.receiptNumber,
    receiptHash: receipt.receiptHash,
    appointmentId: receipt.appointmentId,
    paidAt: receipt.paidAt,
  });

  const qrBuffer = await QRCode.toBuffer(qrPayload, { type: 'png', width: 160, margin: 1 });

  doc.fontSize(22).fillColor('#0f172a').text('MedSync Payment Receipt', { align: 'left' });
  doc.moveDown(0.2);
  doc.fontSize(10).fillColor('#475569').text('Official consultation payment confirmation and payslip', { align: 'left' });

  doc.image(qrBuffer, 410, 44, { width: 130, height: 130 });

  doc.moveDown(2);
  doc.fontSize(12).fillColor('#111827').text(`Receipt No: ${receipt.receiptNumber}`);
  doc.text(`Payment ID: ${receipt.paymentId}`);
  doc.text(`Appointment ID: ${receipt.appointmentId}`);
  doc.text(`Status: ${String(receipt.status || '').toUpperCase()}`);

  doc.moveDown(1);
  doc.fontSize(13).fillColor('#0f172a').text('Payer & Consultation Details');
  doc.moveDown(0.4);
  doc.fontSize(11).fillColor('#111827').text(`Patient ID: ${receipt.patientId}`);
  doc.text(`Doctor: ${receipt.doctorName} (${receipt.doctorId})`);
  doc.text(`Paid At: ${new Date(receipt.paidAt).toLocaleString()}`);

  doc.moveDown(1);
  doc.fontSize(13).fillColor('#0f172a').text('Amount Summary');
  doc.moveDown(0.4);
  doc.fontSize(18).fillColor('#111827').text(receipt.amountLabel);
  doc.fontSize(10).fillColor('#64748b').text(`Amount (raw): ${receipt.amount}`);

  doc.moveDown(1);
  doc.fontSize(13).fillColor('#0f172a').text('Novel Audit Intelligence');
  doc.moveDown(0.4);
  doc.fontSize(11).fillColor('#111827').text(`Risk Score: ${receipt.riskScore}/100`);
  doc.text(`Risk Level: ${String(receipt.riskLevel || 'low').toUpperCase()}`);

  doc.moveDown(1);
  doc.fontSize(9).fillColor('#475569').text('Tamper-evident receipt hash:');
  doc.fontSize(9).fillColor('#1f2937').text(receipt.receiptHash, { width: 500 });

  if (receipt.receiptUrl) {
    doc.moveDown(0.8);
    doc.fontSize(10).fillColor('#2563eb').text(`Receipt URL: ${receipt.receiptUrl}`, {
      link: receipt.receiptUrl,
      underline: true,
    });
  }

  doc.moveDown(2);
  doc.fontSize(9).fillColor('#64748b').text('Generated by MedSync Payment Service', { align: 'center' });

  doc.end();
  return completed;
};

module.exports = {
  generateReceiptNumber,
  signReceiptHash,
  buildReceiptData,
  generateReceiptPdfBuffer,
};
